language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
script:
  - cargo doc
  - cargo doc --features gc
  - cargo build
  - cargo build --features gc
  - cargo build --release
  - cargo build --release --features gc
  - cargo test
  - cargo test --features gc
  - cargo test --release
  - cargo test --release --features gc
  - cargo +nightly test --no-default-features
  - cargo +nightly test --features gc --no-default-features
  - cargo +nightly test --features std --no-default-features
  - cargo +nightly test --features gc,std --no-default-features
  - cargo +nightly test --no-default-features --release
  - cargo +nightly test --features gc --no-default-features --release
  - cargo +nightly test --features std --no-default-features --release
  - cargo +nightly test --features gc,std --no-default-features --release
